- name: database_setup
  hosts: all
  become: yes
  tasks:
    - name: install_my_sql_server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: start_sql_service
      ansible.builtin.systemd_service:
        name: mysqld
        enabled: yes
        state: started

    - name: setup_sql_pwd
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1