- name: get_secrets
  hosts: localhost
  tasks:
    - name: get_ssh_secrets
      ansible.builtin.lineinfile:
        path: /tmp/ssh.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{ vault_token }} url=https://vault.izypsy.cloud:8200 validate_certs=False')}}"
        create: yes