- name: get_secrets
  hosts: localhost
  tasks:
    - name: Fetch secrets from HashiCorp Vault
      hashi_vault:
        token: "{{ vault_token }}"
        url: https://vault.izypsy.cloud:8200
        secret: common/data/ssh
        validate_certs: False
      register: vault_secrets

    - name: Write secrets to JSON file
      copy:
        content: "{{ vault_secrets['data']['data'] | to_nice_json }}"
        dest: /tmp/secret_file.json


#    - name: get_ssh_secrets
#      ansible.builtin.lineinfile:
#        path: ssh.json
#        line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{ vault_token }} url=https://vault.izypsy.cloud:8200 validate_certs=False')}}"
#        create: yes