- name: get_secrets
  hosts: localhost
  tasks:
    - name: get_ssh_secrets
      ansible.builtin.lineinfile:
        path: ~/ssh-secrets.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{ vault_token }} url=https://vault-int.izypsy.cloud:8200 validate_certs=False')}}" # need to change this
        create: yes

    - name: get_app_secrets
      ansible.builtin.lineinfile:
        path: ~/app-secrets.json
        line: "{{ lookup('hashi_vault', 'secret=expense-{{ env }}/data/{{ role_name }} token={{ vault_token }} url=https://vault-int.izypsy.cloud:8200 validate_certs=False')}}"
        create: yes