- name: install_my_sql_server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: start_sql_service
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: yes
    state: started

- name: check_mysql_connect
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: database-{{ env }}.izypsy.cloud
    filter: version
  register: db_status
  ignore_errors: yes

- name: setup_sql_pwd
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
  when: db_status.failed is true