- name: remove_old_content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: create_new_directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory

- name: download_app_content_to_dir
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_loc }}"
    remote_src: yes