format_version: 10
pipelines:
  backend:
    group: expense
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-1ce9e45:
        git: https://github.com/devops-iterration1/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - DEV:
        fetch_materials: true
        environment_variables:
          env: dev
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - backend
                - 172.31.80.61 # host_ip
                - 172.31.80.10  # db_ip
                command: bash
                run_if: passed
    - QA:
        fetch_materials: true
        environment_variables:
          env: qa
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - backend
                - 172.31.81.158
                - 172.31.80.8
                command: bash
                run_if: passed
    - STAGE:
        fetch_materials: true
        environment_variables:
          env: stage
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - backend
                - 172.31.81.158
                - 172.31.80.8
                command: bash
                run_if: passed
    - PROD:
        fetch_materials: true
        environment_variables:
          env: prod
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - backend
                - 172.31.81.158
                - 172.31.80.8
                command: bash
                run_if: passed
