format_version: 10
pipelines:
  frontend:
    group: expense
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-1ce9e45:
        git: https://github.com/devops-iterration1/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:M6lqkRVVkFIgm03FOg+QIA==:wfxF9lLGzjvG+6Fj1KxiPIl49UntMQQ/2oiUn2Eybd4=
    stages:
    - DEV:
        fetch_materials: true
        environment_variables:
          env: dev
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - frontend
                command: bash
                run_if: passed
    - QA:
        fetch_materials: true
        environment_variables:
          env: qa
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - frontend
                - 172.31.80.151
                - 172.31.81.158
                command: bash
                run_if: passed
    - STAGE:
        fetch_materials: true
        environment_variables:
          env: stage
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - frontend
                - 172.31.80.151
                - 172.31.81.158
                command: bash
                run_if: passed
    - PROD:
        fetch_materials: true
        environment_variables:
          env: prod
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - frontend
                - 172.31.80.151
                - 172.31.81.158
                command: bash
                run_if: passed
