format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-1ce9e45:
        git: https://github.com/devops-iterration1/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - DEV:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - -i
                - 172.31.80.8,
                - -e
                - ansible_user=ec2-user
                - -e
                - ansible_password=DevOps321
                - -e
                - role_name=database
                - -e
                - env=dev
                - -e
                - db_ip=172.31.80.8
                - expense_setup.yml
                command: ansible-playbook
                run_if: passed
    - QA:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - frontend
                - 172.31.80.151
                - 172.31.81.158
                command: bash
                run_if: passed
    - STAGE:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - -i
                - 172.31.80.8,
                - -e
                - ansible_user=ec2-user
                - -e
                - ansible_password=DevOps321
                - -e
                - role_name=database
                - -e
                - env=dev
                - -e
                - db_ip=172.31.80.8
                - expense_setup.yml
                command: ansible-playbook
                run_if: passed
    - PROD:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          database:
            tasks:
            - exec:
                arguments:
                - -i
                - 172.31.80.8,
                - -e
                - ansible_user=ec2-user
                - -e
                - ansible_password=DevOps321
                - -e
                - role_name=database
                - -e
                - env=dev
                - -e
                - db_ip=172.31.80.8
                - expense_setup.yml
                command: ansible-playbook
                run_if: passed
